# Generated by Django 5.0.6 on 2024-06-29 23:17

import django.utils.timezone
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('tiendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
